version: '3.8'

services:
  app:
    restart: always
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
