version: '3.8'

services:
  app-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      - SPOXY_REDIS_URL=redis://redis:6379/0
      - SPOXY_PROXY_URL=${SPOXY_PROXY_URL:-}
    depends_on:
      - redis
    # Security capabilities for Delve/Ptrace
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
